from __future__ import annotations

from typing import Any

from i18n import t


FONT_STACK = '"Lato", "Noto Sans Hebrew", "Rubik", "Segoe UI Variable", "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont, sans-serif'

THEME_OPTIONS = ("light", "dark", "system")

REQUIRED_THEME_KEYS = {
    "bg",
    "page_bg",
    "shell_bg",
    "sidebar_bg",
    "workbench_bg",
    "surface",
    "surface_alt",
    "panel_bg",
    "card_bg",
    "elevated_card_bg",
    "input_bg",
    "input_border",
    "text",
    "text_primary",
    "text_secondary",
    "muted",
    "disabled_text",
    "border",
    "border_soft",
    "shadow",
    "gradient",
    "primary",
    "accent",
    "local",
    "advisory",
    "info",
    "success",
    "warning",
    "danger",
    "primary_soft",
    "button_primary_bg",
    "button_primary_text",
    "button_secondary_bg",
    "button_secondary_text",
    "button_secondary_border",
    "button_ghost_bg",
    "button_ghost_text",
    "button_ghost_border",
    "button_danger_bg",
    "button_danger_text",
    "button_danger_border",
    "button_disabled_bg",
    "button_disabled_text",
    "button_disabled_border",
    "button_download_bg",
    "button_download_text",
    "button_download_border",
    "focus_ring",
    "state_info_bg",
    "state_warning_bg",
    "state_success_bg",
    "state_danger_bg",
    "loading",
    "loading_border",
    "loading_deterministic",
    "loading_local_ai",
    "loading_simulation",
    "loading_export",
    "critical",
    "high",
    "medium",
    "low",
}

THEMES: dict[str, dict[str, str]] = {
    "light": {
        "bg": "#F3F7FA",
        "page_bg": "#F3F7FA",
        "shell_bg": "#EAF1F7",
        "sidebar_bg": "#E8F0F6",
        "workbench_bg": "#FBFCFE",
        "surface": "#FFFFFF",
        "surface_alt": "#F6F9FC",
        "panel_bg": "#FBFCFE",
        "card_bg": "#FFFFFF",
        "elevated_card_bg": "#F8FBFF",
        "input_bg": "#FFFFFF",
        "input_border": "#AEBFD2",
        "text": "#102033",
        "text_primary": "#102033",
        "text_secondary": "#35465A",
        "muted": "#637184",
        "disabled_text": "#718096",
        "border": "#CBD8E6",
        "border_soft": "#E2EAF3",
        "shadow": "rgba(18, 34, 53, 0.12)",
        "gradient": "linear-gradient(135deg, #0B4F6C 0%, #0F7B8A 100%)",
        "primary": "#0B4F6C",
        "accent": "#0F7B8A",
        "local": "#008A6A",
        "advisory": "#7A4EAB",
        "info": "#246BFE",
        "success": "#087F5B",
        "warning": "#A86600",
        "danger": "#A61B3D",
        "primary_soft": "#E4F1F7",
        "accent_soft": "#E2F7F6",
        "button_primary_bg": "linear-gradient(135deg, #0B4F6C 0%, #0F7B8A 100%)",
        "button_primary_text": "#FFFFFF",
        "button_secondary_bg": "#FFFFFF",
        "button_secondary_text": "#102033",
        "button_secondary_border": "#9EB4D0",
        "button_ghost_bg": "transparent",
        "button_ghost_text": "#0B4F6C",
        "button_ghost_border": "#C8D5E5",
        "button_danger_bg": "#A61B3D",
        "button_danger_text": "#FFFFFF",
        "button_danger_border": "#7F1630",
        "button_disabled_bg": "#E7ECF3",
        "button_disabled_text": "#718096",
        "button_disabled_border": "#CBD5E1",
        "button_download_bg": "#E2F7F6",
        "button_download_text": "#0A5C63",
        "button_download_border": "#75C7C0",
        "focus_ring": "#1677A3",
        "state_info_bg": "#E4F1F7",
        "state_warning_bg": "#FFF8E7",
        "state_success_bg": "#E9FBF4",
        "state_danger_bg": "#FFF0F5",
        "loading": "#0B4F6C",
        "loading_border": "#86ADC4",
        "loading_deterministic": "#0B4F6C",
        "loading_local_ai": "#7A4EAB",
        "loading_simulation": "#A86600",
        "loading_export": "#0F7B8A",
        "critical": "#A61B3D",
        "high": "#D94720",
        "medium": "#A86600",
        "low": "#087F5B",
        "critical_soft": "#FFF0F5",
        "high_soft": "#FFF2ED",
        "medium_soft": "#FFF8E7",
        "low_soft": "#E9FBF4",
        "critical_border": "#E999B7",
        "high_border": "#F0A58E",
        "medium_border": "#E9C270",
        "low_border": "#80CDB4",
        "calculated": "#0B4F6C",
        "calculated_soft": "#E4F1F7",
        "calculated_border": "#91B3E8",
        "detected": "#1463B8",
        "detected_soft": "#E8F3FF",
        "detected_border": "#91BCE8",
        "simulated": "#A86600",
        "simulated_soft": "#FFF8E7",
        "simulated_border": "#E9C270",
        "recommended": "#087F5B",
        "recommended_soft": "#E9FBF4",
        "recommended_border": "#80CDB4",
        "uncertain": "#5D6879",
        "uncertain_soft": "#F0F3F7",
        "uncertain_border": "#B7C0CE",
        "bg_app_light": "#F3F7FA",
        "bg_app_dark": "#09131F",
        "bg_shell_light": "#EAF1F7",
        "bg_shell_dark": "#111C2B",
        "bg_workbench_light": "#FBFCFE",
        "bg_workbench_dark": "#111C2A",
        "bg_card_light": "#FFFFFF",
        "bg_card_dark": "#152233",
        "text_primary_light": "#102033",
        "text_primary_dark": "#F5F8FC",
        "text_secondary_light": "#35465A",
        "text_secondary_dark": "#C8D5E5",
        "border_default_light": "#CBD8E6",
        "border_default_dark": "#314256",
        "focus_ring_light": "#1677A3",
        "focus_ring_dark": "#8DB8FF",
        "primary_action": "#0B4F6C",
        "secondary_action": "#FFFFFF",
        "tertiary_action": "#F6F9FC",
        "ghost_action": "transparent",
        "danger_action": "#A61B3D",
        "warning_status": "#A86600",
        "success_status": "#087F5B",
        "local_status": "#087F5B",
        "advisory_status": "#7A4EAB",
        "severity_low": "#087F5B",
        "severity_medium": "#A86600",
        "severity_high": "#D94720",
        "radius_sm": "6px",
        "radius_md": "8px",
        "radius_lg": "12px",
        "radius_xl": "16px",
        "spacing_xs": "0.35rem",
        "spacing_sm": "0.65rem",
        "spacing_md": "1rem",
        "spacing_lg": "1.35rem",
        "spacing_xl": "1.85rem",
        "shadow_sm": "0 8px 20px rgba(18, 34, 53, 0.10)",
        "shadow_md": "0 18px 46px rgba(18, 34, 53, 0.12)",
        "shadow_lg": "0 24px 64px rgba(18, 34, 53, 0.15)",
        "font_body": FONT_STACK,
        "font_heading": FONT_STACK,
        "font_mono": "ui-monospace, SFMono-Regular, Consolas, monospace",
    },
    "dark": {
        "bg": "#09131F",
        "page_bg": "#09131F",
        "shell_bg": "#111C2B",
        "sidebar_bg": "#0F1A28",
        "workbench_bg": "#111C2A",
        "surface": "#111C2B",
        "surface_alt": "#172638",
        "panel_bg": "#121E2D",
        "card_bg": "#152233",
        "elevated_card_bg": "#1A2A3D",
        "input_bg": "#0D1724",
        "input_border": "#43566D",
        "text": "#F5F8FC",
        "text_primary": "#F5F8FC",
        "text_secondary": "#C8D5E5",
        "muted": "#A5B4C7",
        "disabled_text": "#7D8CA1",
        "border": "#314256",
        "border_soft": "#233447",
        "shadow": "rgba(3, 9, 18, 0.48)",
        "gradient": "linear-gradient(135deg, #76B7D6 0%, #2ED3C6 100%)",
        "primary": "#76B7D6",
        "accent": "#2ED3C6",
        "local": "#4BD4A0",
        "advisory": "#C6A2FF",
        "info": "#8DB8FF",
        "success": "#43D6A3",
        "warning": "#F5BC4A",
        "danger": "#FF6B9C",
        "primary_soft": "rgba(110, 168, 255, 0.15)",
        "accent_soft": "rgba(45, 212, 191, 0.14)",
        "button_primary_bg": "linear-gradient(135deg, #2F6FD0 0%, #087F74 100%)",
        "button_primary_text": "#FFFFFF",
        "button_secondary_bg": "#182434",
        "button_secondary_text": "#F3F6FC",
        "button_secondary_border": "#4E6076",
        "button_ghost_bg": "rgba(110, 168, 255, 0.08)",
        "button_ghost_text": "#B9D4FF",
        "button_ghost_border": "#34445A",
        "button_danger_bg": "#B4235A",
        "button_danger_text": "#FFFFFF",
        "button_danger_border": "#FF6B9C",
        "button_disabled_bg": "#101824",
        "button_disabled_text": "#7D8CA1",
        "button_disabled_border": "#2E3A48",
        "button_download_bg": "rgba(45, 212, 191, 0.13)",
        "button_download_text": "#D5FFF7",
        "button_download_border": "rgba(45, 212, 191, 0.48)",
        "focus_ring": "#8DB8FF",
        "state_info_bg": "rgba(110, 168, 255, 0.15)",
        "state_warning_bg": "rgba(245, 188, 74, 0.14)",
        "state_success_bg": "rgba(67, 214, 163, 0.14)",
        "state_danger_bg": "rgba(255, 107, 156, 0.14)",
        "loading": "#76B7D6",
        "loading_border": "rgba(118, 183, 214, 0.48)",
        "loading_deterministic": "#76B7D6",
        "loading_local_ai": "#C6A2FF",
        "loading_simulation": "#F5BC4A",
        "loading_export": "#2ED3C6",
        "critical": "#FF6B9C",
        "high": "#FF835E",
        "medium": "#F5BC4A",
        "low": "#43D6A3",
        "critical_soft": "rgba(255, 107, 156, 0.14)",
        "high_soft": "rgba(255, 131, 94, 0.14)",
        "medium_soft": "rgba(245, 188, 74, 0.14)",
        "low_soft": "rgba(67, 214, 163, 0.14)",
        "critical_border": "rgba(255, 107, 156, 0.48)",
        "high_border": "rgba(255, 131, 94, 0.48)",
        "medium_border": "rgba(245, 188, 74, 0.48)",
        "low_border": "rgba(67, 214, 163, 0.48)",
        "calculated": "#8DB8FF",
        "calculated_soft": "rgba(110, 168, 255, 0.15)",
        "calculated_border": "rgba(141, 184, 255, 0.46)",
        "detected": "#72B7FF",
        "detected_soft": "rgba(114, 183, 255, 0.14)",
        "detected_border": "rgba(114, 183, 255, 0.46)",
        "simulated": "#F5BC4A",
        "simulated_soft": "rgba(245, 188, 74, 0.14)",
        "simulated_border": "rgba(245, 188, 74, 0.48)",
        "recommended": "#43D6A3",
        "recommended_soft": "rgba(67, 214, 163, 0.14)",
        "recommended_border": "rgba(67, 214, 163, 0.48)",
        "uncertain": "#C1CCDC",
        "uncertain_soft": "rgba(149, 165, 188, 0.13)",
        "uncertain_border": "rgba(149, 165, 188, 0.42)",
        "bg_app_light": "#F5F7FB",
        "bg_app_dark": "#09131F",
        "bg_shell_light": "#EEF3F8",
        "bg_shell_dark": "#111C2B",
        "bg_workbench_light": "#FFFFFF",
        "bg_workbench_dark": "#111C2A",
        "bg_card_light": "#FFFFFF",
        "bg_card_dark": "#121C29",
        "text_primary_light": "#111827",
        "text_primary_dark": "#F3F6FC",
        "text_secondary_light": "#3F4D63",
        "text_secondary_dark": "#C5D0E0",
        "border_default_light": "#D5DFEA",
        "border_default_dark": "#2E3A48",
        "focus_ring_light": "#174EA6",
        "focus_ring_dark": "#8DB8FF",
        "primary_action": "#2F6FD0",
        "secondary_action": "#182434",
        "tertiary_action": "#172231",
        "ghost_action": "rgba(110, 168, 255, 0.08)",
        "danger_action": "#B4235A",
        "warning_status": "#F5BC4A",
        "success_status": "#43D6A3",
        "local_status": "#43D6A3",
        "advisory_status": "#F5BC4A",
        "severity_low": "#43D6A3",
        "severity_medium": "#F5BC4A",
        "severity_high": "#FF835E",
        "radius_sm": "6px",
        "radius_md": "8px",
        "radius_lg": "12px",
        "radius_xl": "16px",
        "spacing_xs": "0.35rem",
        "spacing_sm": "0.65rem",
        "spacing_md": "1rem",
        "spacing_lg": "1.35rem",
        "spacing_xl": "1.85rem",
        "shadow_sm": "0 8px 20px rgba(3, 9, 18, 0.38)",
        "shadow_md": "0 18px 46px rgba(3, 9, 18, 0.44)",
        "shadow_lg": "0 24px 64px rgba(3, 9, 18, 0.52)",
        "font_body": FONT_STACK,
        "font_heading": FONT_STACK,
        "font_mono": "ui-monospace, SFMono-Regular, Consolas, monospace",
    },
}
THEMES["system"] = dict(THEMES["light"])

REQUIRED_2026_TOKEN_KEYS = {
    "bg_app_light",
    "bg_app_dark",
    "bg_shell_light",
    "bg_shell_dark",
    "bg_workbench_light",
    "bg_workbench_dark",
    "bg_card_light",
    "bg_card_dark",
    "text_primary_light",
    "text_primary_dark",
    "text_secondary_light",
    "text_secondary_dark",
    "border_default_light",
    "border_default_dark",
    "focus_ring_light",
    "focus_ring_dark",
    "primary_action",
    "secondary_action",
    "tertiary_action",
    "ghost_action",
    "danger_action",
    "warning_status",
    "success_status",
    "local_status",
    "advisory_status",
    "severity_low",
    "severity_medium",
    "severity_high",
    "radius_sm",
    "radius_md",
    "radius_lg",
    "radius_xl",
    "spacing_xs",
    "spacing_sm",
    "spacing_md",
    "spacing_lg",
    "spacing_xl",
    "shadow_sm",
    "shadow_md",
    "shadow_lg",
    "font_body",
    "font_heading",
    "font_mono",
}

REQUIRED_THEME_KEYS = REQUIRED_THEME_KEYS | REQUIRED_2026_TOKEN_KEYS

COLORS: dict[str, str] = {
    "surface": "var(--aiwra-surface)",
    "card": "var(--aiwra-card-bg)",
    "elevated": "var(--aiwra-elevated-card-bg)",
    "surface_soft": "var(--aiwra-surface-alt)",
    "surface_muted": "var(--aiwra-surface-alt)",
    "border": "var(--aiwra-border)",
    "border_soft": "var(--aiwra-border)",
    "text": "var(--aiwra-text)",
    "muted": "var(--aiwra-muted)",
    "blue": "var(--aiwra-primary)",
    "blue_soft": "var(--aiwra-primary-soft)",
    "green": "var(--aiwra-low)",
    "green_soft": "var(--aiwra-low-soft)",
    "amber": "var(--aiwra-medium)",
    "amber_soft": "var(--aiwra-medium-soft)",
    "red": "var(--aiwra-critical)",
    "red_soft": "var(--aiwra-critical-soft)",
    "purple": "var(--aiwra-accent)",
    "purple_soft": "var(--aiwra-calculated-soft)",
    "gray": "var(--aiwra-uncertain)",
    "gray_soft": "var(--aiwra-uncertain-soft)",
}


SEVERITY_TOKENS: dict[str, dict[str, str]] = {
    "low": {
        "label_key": "risk_level_low",
        "description_key": "severity_low_description",
        "color": COLORS["green"],
        "background": COLORS["green_soft"],
        "border": "var(--aiwra-low-border)",
    },
    "medium": {
        "label_key": "risk_level_medium",
        "description_key": "severity_medium_description",
        "color": COLORS["amber"],
        "background": COLORS["amber_soft"],
        "border": "var(--aiwra-medium-border)",
    },
    "high": {
        "label_key": "risk_level_high",
        "description_key": "severity_high_description",
        "color": "var(--aiwra-high)",
        "background": "var(--aiwra-high-soft)",
        "border": "var(--aiwra-high-border)",
    },
    "critical": {
        "label_key": "risk_level_critical",
        "description_key": "severity_critical_description",
        "color": COLORS["red"],
        "background": COLORS["red_soft"],
        "border": "var(--aiwra-critical-border)",
    },
    "unknown": {
        "label_key": "risk_level_unknown",
        "description_key": "severity_unknown_description",
        "color": COLORS["gray"],
        "background": COLORS["gray_soft"],
        "border": "var(--aiwra-uncertain-border)",
    },
}


STATUS_TOKENS: dict[str, dict[str, str]] = {
    "detected": {
        "label_key": "status_detected_label",
        "description_key": "status_detected_description",
        "color": "var(--aiwra-detected)",
        "background": "var(--aiwra-detected-soft)",
        "border": "var(--aiwra-detected-border)",
    },
    "calculated": {
        "label_key": "status_calculated_label",
        "description_key": "status_calculated_description",
        "color": COLORS["purple"],
        "background": COLORS["purple_soft"],
        "border": "var(--aiwra-calculated-border)",
    },
    "simulated": {
        "label_key": "status_simulated_label",
        "description_key": "status_simulated_description",
        "color": "var(--aiwra-simulated)",
        "background": "var(--aiwra-simulated-soft)",
        "border": "var(--aiwra-simulated-border)",
    },
    "recommended": {
        "label_key": "status_recommended_label",
        "description_key": "status_recommended_description",
        "color": "var(--aiwra-recommended)",
        "background": "var(--aiwra-recommended-soft)",
        "border": "var(--aiwra-recommended-border)",
    },
    "uncertain": {
        "label_key": "status_uncertain_label",
        "description_key": "status_uncertain_description",
        "color": COLORS["gray"],
        "background": COLORS["gray_soft"],
        "border": "var(--aiwra-uncertain-border)",
    },
    "needs_human_review": {
        "label_key": "status_needs_human_review_label",
        "description_key": "status_needs_human_review_description",
        "color": COLORS["amber"],
        "background": COLORS["amber_soft"],
        "border": "var(--aiwra-medium-border)",
    },
    "read_only": {
        "label_key": "status_read_only_label",
        "description_key": "status_read_only_description",
        "color": COLORS["gray"],
        "background": COLORS["gray_soft"],
        "border": "var(--aiwra-uncertain-border)",
    },
    "demo": {
        "label_key": "status_demo_label",
        "description_key": "status_demo_description",
        "color": COLORS["blue"],
        "background": COLORS["blue_soft"],
        "border": "var(--aiwra-primary)",
    },
    "local_only": {
        "label_key": "status_local_only_label",
        "description_key": "status_local_only_description",
        "color": COLORS["green"],
        "background": COLORS["green_soft"],
        "border": "var(--aiwra-low-border)",
    },
    "not_available": {
        "label_key": "status_not_available_label",
        "description_key": "status_not_available_description",
        "color": COLORS["gray"],
        "background": COLORS["gray_soft"],
        "border": "var(--aiwra-uncertain-border)",
    },
}


def normalize_severity(severity: object) -> str:
    key = str(severity or "unknown").casefold().strip()
    return key if key in SEVERITY_TOKENS else "unknown"


def normalize_status(status: object) -> str:
    key = str(status or "uncertain").casefold().strip().replace("-", "_").replace(" ", "_")
    return key if key in STATUS_TOKENS else "uncertain"


def normalize_theme(theme: object) -> str:
    key = str(theme or "system").casefold().strip()
    return key if key in THEME_OPTIONS else "system"


def resolved_theme(theme: object) -> str:
    key = normalize_theme(theme)
    return "light" if key == "system" else key


def theme_tokens(theme: object = "light") -> dict[str, str]:
    return THEMES[resolved_theme(theme)].copy()


def theme_label(theme: object, language: str = "en") -> str:
    key = normalize_theme(theme)
    return t(f"theme_{key}", language, key.title())


def severity_token(severity: object, language: str = "en") -> dict[str, Any]:
    key = normalize_severity(severity)
    token = dict(SEVERITY_TOKENS[key])
    token.update(
        {
            "key": key,
            "label": t(token["label_key"], language, key.title()),
            "description": t(token["description_key"], language, ""),
        }
    )
    return token


def status_token(status: object, language: str = "en") -> dict[str, Any]:
    key = normalize_status(status)
    token = dict(STATUS_TOKENS[key])
    token.update(
        {
            "key": key,
            "label": t(token["label_key"], language, key.replace("_", " ").title()),
            "description": t(token["description_key"], language, ""),
        }
    )
    return token


def color_css_variables(theme: object = "light") -> str:
    tokens = theme_tokens(theme)
    aliases = {
        "surface-soft": tokens["surface_alt"],
        "surface-muted": tokens["surface_alt"],
        "card": tokens["card_bg"],
        "elevated": tokens["elevated_card_bg"],
        "blue": tokens["primary"],
        "blue-soft": tokens["primary_soft"],
        "green": tokens["low"],
        "green-soft": tokens["low_soft"],
        "amber": tokens["medium"],
        "amber-soft": tokens["medium_soft"],
        "red": tokens["critical"],
        "red-soft": tokens["critical_soft"],
        "purple": tokens["calculated"],
        "purple-soft": tokens["calculated_soft"],
        "gray": tokens["uncertain"],
        "gray-soft": tokens["uncertain_soft"],
    }
    variables = [f"--aiwra-{name.replace('_', '-')}: {value};" for name, value in tokens.items()]
    variables.extend(f"--aiwra-{name}: {value};" for name, value in aliases.items())
    return "\n".join(variables)
